### ISSUE TITLE
github: faulty webhook payload release tracking logic

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo#2266]
GitHub has added a couple [of different `action` types](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#webhook-payload-object-38) for releases. We are currently only listening for the `published` action, but apparently `created` and `released` are likely candidates for capturing releases as well. We should:

- [ ] Try out different ways of creating/publishing releasing and inspect their webhook event payloads
- [ ] Decide which `action` types should trigger the record publishing workflow
- [ ] Take care not to double-trigger the publishing workflow (probably we're protected because of [this check](https://github.com/inveniosoftware/invenio-github/blob/883eb122fb13dc09fc28c1de25bfb435bee2db56/invenio_github/models.py#L315-L320))

(For internal checks see example production Event payload with ID `6f18a540-ec10-4fac-b482-7574cf2e1ead`)
