### ISSUE TITLE
records: DOI  versioning integration checklist

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo#954]
Currently adding versioning to Zenodo requires a variety of changes throughout Deposit API, DOI/Datacite registration, management tasks (deleting/moving records), etc. Here's a list of such cases and their affecting components:

### Deposits/Records API

- [x] New records should also be coupled with creation of a new Concept PID
  - [x] Concept PIDs should get their Recid minted first, to keep a logical order (Concept PID > Version PID)
- [x] Creation of a new version:
  - [x] Create copy of metadata - Strip/regenerate certain fields ('_deposit', 'doi', '_oai', '_files', '_buckets', '$schema')
  - [x] Create unlocked snapshot of bucket
- [x] Record metadata (JSON Schema) may need additional fields:
  - [x] "conceptdoi" (Concept DOI) - manually added to the record metadata at minting
  - [x] "conceptrecid" (Concept recid) - same as "conceptdoi"
- [x] Editing older versions:
  - [x] Disallow editing communities
- [x] Disallow creating new versions of Custom DOIs
- [x] Disallow creating a new version if the files have not been modified or if the bucket contents is the same as one of the previous versions (e.g. adding a file in one version, then removing it the same as creating a duplicate record). (**Prod**, 2h)
- Creating new version requires opening the last one in draft mode (in which it stays). Perhaps new version should be done from the Record view also?
    - [x] Discard "current" deposit draft when clicking "New Version" from the deposit form (uses modal prompt to inform the user)
 - [x] Create a new "New Version" button on the Record page, so it's only kept in draft if user went through "Edit" first (which is fine). (**Prod**, 0.5h)**
- [x] Deleting record in versioning
  - [x] Deleting a last version should update Datacite information.
- [x] Non-versioned deposit  should create new versioning info on publish/save actions (lazy upon action call).
- [x] Non-versioned records should  create new versioning info on new version.
- [x] Non-Zenodo DOI
  - [x] Adding custom DOI new version of a versioned record shouldn't be allowed - On `deposit.newversion` pre-reserve Zenodo DOI immediately
- [x] Serialized result contains empty relations key when the record is not versioned (`relations: {}`)

### UI/UX

- [x] Search facets - All Versions Toggle
- Fixing deposit-ui issues
  - [x] Generation of links from ES (search) and DB (single record serialization) (**Prod**)
   - [x] bulk-index all children upon publishing so that the draft_child and draft_child_deposit information is reindexed properly for all siblings. (**0.5h, Prod**)
  - [x] Filter/Search by Concept-only/All-Versions. Integrate search facets in the same way they appear in regular record search (**QA**, 4h)
  - [x] Custom indexer function which indexes all non-versioned records as "latest" version (**QA**, 2h)
  - [x] Clicking "Discard Changes" does not redirect properly.
- Upload page redesign for deposit results list. Users should be able to:
  - [x] Be able to clearly see in what status each record/deposit is, and generally get more information about each entry (**Prod**)
- [x] Record view page
  - [x] Make blue alert box on top of page similar to the wide screen alert of flashed messages
  - [x] Change phrasing of alert box to "There are other versions of this record. The latest is available here"
  - [x] Make version dropdown more intuitive about current/latest record versions
  - [x] Make version dropdown handle many versions (eg. add scrollbar)
  - [x] New version dialog on deposit should not mention Concept DOI, but state that:
    - It's intended only for updating files, and that use should return back to the form is he intends to update the metadata only
    - A continuing with New Version will create a new deposit, which upon publishing will have a new DOI
  - [x] Lower-case the labels and buttons text "New Version" -> "New version", "Record Versions" -> "Record versions", etc.
  - [x] Yellow warning color on the flash box on "There exists new version", both on record page and deposit.
  - [x] Change badges on the search result ``Version 2 (latest)`` -> ``DATE (v2)`` (merge with date badge)
  - [x] Deposit sort by Versions
  - [ ] ~~Badge caching issue (#912)~~ (doesn't affect DOI badges atm)

### DOI/Datacite

- [x] Registration of Concept DOI to DataCite (same as registration of regular one).
- Decide on what kind of metadata the Concept DOI will hold (copy of the latest version)
  - [x] What happens when the latest Version PID is modified - the metadata should be updated for the Concept DOI in DataCite as well
  - Fill-in Related Identifiers metadata on Zenodo at versioning
    - [x] ``isNewVersionOf``/``isPreviousVersionOf``: If we serialize these we have to update the metadata for previous/next objects in the linked list upon creation/deletion of new versions.
     - [x] Comment this out for now because of semantic versioning records (e.g. GitHub)
    - [x] ``hasVersions/isVersionOf`` - **DataCite 4.x sprint LATER**
    - [x] ``isPartOf``/``hasPart``: Has similar issues with the above, but not at such a large scale. (**QA**)
 - [x] Add single-record serialization of relations in DublinCore and Marc21 in OAI-PMH 
### Elasticsearch/Indexing

- [x] New mappings for records and deposits, with necessary fields to make searches possible

### REST API

- [x] Version-aware `/api/records` endpoint
  - [x] Filters
  - [x] Links generation
- [x] ``/api/deposit/newversion?recid=134`` vs ``/api/deposit/123/actions/newversion``
- [x] 'concept_doi' nor 'concept_record_id' are returned in the JSON response (see value of ``data`` here: https://github.com/zenodo/zenodo/blob/master/tests/unit/deposit/test_api_editflow.py#L402). We should return those as well

### Communities

- Are communities listing only the last version of the record? If so, what if a community is removed at some point in the version-history - does it disappear? Solutions:
  - [x] Propagate "community" metadata changes to all version.
    - [x] Resolving any InclusionRequest (of any version) is propagated for all versions
    - [x] Checking if IR exists should be done for any of siblings
  - [x] Lock editing of communities to only the latest version (both agular schema form and REST API validation). (**Not required anymore**)
  - [x] Propagate changes to the new version draft as well (currently propagating across published versions only) (**QA**, 1h)

### GitHub

- [x] Subsequent repository releases should be in a versioning scheme on Zenodo. (**Prod**, 2d)
- Allow to manually publish new versions of GitHub records
  - [x]  Insert new GitHub release while allowing for the new version draft to be open (circumvent the limitation) OR fail and leave a notification on the Release object. (**Prod**, 1d)
    - [x] IF going for failing - implement a retry button (**Prod**, 2h)
- [x] Condition on creating New version to be an owner of the latest_version of the record in the versioning scheme (old GitHub repo owners shouldn't be able to manually create new record versions). If the record is GitHub-originated, check for the newest owner(**Prod**, 2h)
- [x] Migrate old GitHub records/deposit into a versioning-scheme. (**Prod**, 1-2d)
  - [x] Migrated GitHub records need to be synchronize their community membership (union of all communities), and propagated to deposits too.

### Misc

- [ ] Profile performance and DB usage throughout views and endpoints
- [ ] Management of versioned records as part of support (deleting, changing files, etc)
- [ ] Citation generation for Concept PID
- [x] Also include date of version in the "Record Versions" dropdown
- [x] Documentation/Guides/Blogpost

### Migration of Zenodo data

- [x] Decide if we mint Concept recid for each record, and prepare a migration script (**No/Not needed** - we will not migrate all of old records - they will get conceptdoi/recid information per request or per first new version).

1. Versioned vs Non-versioned records.
   1. All of the old records stay as they are. No batch migration will be done.
   1. All new records will already be "versioned". Versioned records will have a registered Concept DOI and Concept recid. 
   - [x] Each non-versioned record will display a "Convert to a versioned Record" button on the record page and deposit item list. Conversion will supplement the existing records with those, while all new records will get those at first publishing.

### Testing
- Unit tests:
  - [ ] Write unit testing for Zenodo-specific versioning API parts
  - [ ] Write unit test for new-version cases (create new version, delete draft, edit old metadata)
    - Some of it might be already done, but needs checking.
  - [x] Fix communities merging unit tests
- Manual testing:
  - [ ] Test GitHub releases edge cases (changing repository owners, manual new versions, etc)
  - [ ] UI Tests, either manually or write up some simple template-redering tests
    - [ ] Migrated GitHub records should display one InclusionRequest/Community
- [ ] Test Non-versioned deposits actions
- [ ] Non-Zenodo DOI records actions
  - [ ] Versioned deposits
  - [ ] Non-versioned deposits

- [ ] Missing tests:
  - [x] Related identifier serialization
  - [ ] Test eager vs bulk_indexing of siblings (whether they are actually indexed in bulk, use mock)
